# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TA_UI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'JSQMessagesViewController'

  target 'TA_UITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TA_UIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
