# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Taschenanwalt UI Prototyp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Taschenanwalt UI Prototyp

  target 'Taschenanwalt UI PrototypTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Taschenanwalt UI PrototypUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
